heat_template_version: 2014-10-16

# This file taken from: https://raw.githubusercontent.com/cybertron/openstack-virtual-baremetal/master/templates/baremetal-ports-default.yaml

parameters:

  baremetal_prefix:
    type: string

  provision_net:
    type: string

  public_net:
    type: string
    description: Name of external network
    default: public

  suffix:
    type: string

resources:

  provision_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - ''
        - - {get_param: baremetal_prefix}
          - {get_param: suffix}
      network: {get_param: provision_net}

outputs:
  ports:
    value:
    - {port: {get_resource: provision_port}}
