- name: Remove stack
  heat_stack:
    stack_name: "{{ provisioner.stack_name }}"
    state: absent
    login_username: "{{ provisioner.username }}"
    login_password: "{{ provisioner.password }}"
    auth_url: "{{ provisioner.auth_url }}"
    tenant_name: "{{ provisioner.tenant_name }}"
  ignore_errors: true

- name: Remove undercloud image
  glance:
    auth_url: "{{ provisioner.auth_url }}"
    username: "{{ provisioner.username }}"
    tenant_name: "{{ provisioner.tenant_name }}"
    password: "{{ provisioner.password }}"
    name: "{{ tmp.node_prefix }}undercloud.qcow2"
    file: "{{ local_working_dir }}/{{ tmp.node_prefix }}undercloud.qcow2"
    format: qcow2
    state: absent

