---
- name: copy both public and private ssh keys to root directory
  copy:
      src: "{{ lookup('env','HOME') }}/.ssh/{{ item }}"
      dest: "/root/.ssh/{{ item }}"
      mode: 0600
  with_items:
      - id_rsa
      - id_rsa.pub

- name: Set MTU values
  shell: >
      ip link set {{ item }} mtu {{ provisioner.interface.mtu }};
      echo "MTU={{ provisioner.interface.mtu }}" >> /etc/sysconfig/network-scripts/ifcfg-{{ item }}
  with_items: "{{ provisioner.interface.names }}"
