- name: Remove undercloud image
  glance:
    auth_url: "{{ provisioner.auth_url }}"
    username: "{{ provisioner.username }}"
    tenant_name: "{{ provisioner.tenant_name }}"
    password: "{{ provisioner.password }}"
    name: "{{ tmp.node_prefix }}undercloud.qcow2"
    file: "{{ local_working_dir }}/{{ tmp.node_prefix }}undercloud.qcow2"
    format: qcow2
    state: absent

