- name: Remove stack
  os_stack:
      stack_name: "{{ stack_name }}"
      auth:
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_tenant_name }}"
          auth_url: "{{ os_auth_url }}"
      state: absent
  ignore_errors: true

