---
- name: copy both public and private ssh keys to root directory
  become: yes
  copy:
      src: "{{ lookup('env','HOME') }}/.ssh/{{ item }}"
      dest: "/root/.ssh/{{ item }}"
      mode: 0600
  with_items:
      - id_rsa
      - id_rsa.pub

- name: Copy instackenv.json to undercloud
  copy:
    src="{{ local_working_dir }}/nodes.json"
    dest="{{ working_dir }}/instackenv.json"

- name: Set MTU values
  become: yes
  shell: >
      ip link set {{ item }} mtu {{ mtu }};
      echo "MTU={{ mtu }}" >> /etc/sysconfig/network-scripts/ifcfg-{{ item }}
  with_items: "{{ mtu_interface }}"

- name: add nameserver to resolv.conf
  become: yes
  lineinfile:
    dest: /etc/resolv.conf
    iline: nameserver {{ pvt_nameserver }}
